# Generated by Django 3.1.7 on 2021-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('marks', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
